name: Create Archive
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      version:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Release version'
        # Default value if no value is explicitly provided
        default: 'v0.0.1(alpha)'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello Kyle!"
      
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          RELEASE="${{ github.event.inputs.version }}"
          RELEASE_TITLE="${{ github.event.inputs.version }}"
          cd ./terraform
          zip -r ./releases/tf-release.zip ./data ./main.tf ./README.md ./terraform.tfvars ./variables.tf
          gh release create $RELEASE --title $RELEASE_TITLE --notes "This is an alpha release" --prerelease -R kylemoorehead-pingidentity/Master-Flow
          gh release upload $RELEASE ./releases/tf-release.zip -R kylemoorehead-pingidentity/Master-Flow
      
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
