name: Create Release Zip
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      version:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Release version'
        # Default value if no value is explicitly provided
        default: 'v0.0.5(alpha)'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string
jobs:      
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Zip Directory
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: 'tf-release.zip'
          exclusions: '*.git* *.DS_* /images/* TODO.md .editorconfig'
          directory: 'terraform'
      - run: |
          ls
          RELEASE="${{ github.event.inputs.version }}"
          RELEASE_TITLE="${{ github.event.inputs.version }}"
          gh release create $RELEASE --title $RELEASE_TITLE --notes "This is an alpha release" --prerelease -R kylemoorehead-pingidentity/Master-Flow
          gh release upload $RELEASE ./terraform/tf-release.zip -R kylemoorehead-pingidentity/Master-Flow
      
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
